[package]
name = "batchman"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
log = "0.4.26"
log4rs = "1.3.0"
sea-orm = { version = "~1.1.7", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
tokio = { version = "1", features = ["full"] }
