[package]
name = "batchman"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "~1.1.7", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
tokio = { version = "1", features = ["full"] }